### ISSUE TITLE
"Add to favourites" functionality is being stored globally and shared by all users

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#116]
When the user is not logged in, clicking the "Add to favourites" button still works, and the listing will be marked as favourite. 

![image](https://github.com/CMPT276-Project-Group-6/Realtorest/assets/57166217/d0a726b2-c754-42f0-bf5a-042bbf0b25a2)

This seems to be caused by the `is_favourite` attribute in the properties table in db. This means that every single person who is visiting the website will share a single favourite collection. I don't think this is the intended behavior.

**Comment by kzcheng** [comment]
Also, when a user who is not logged in clicks the add to favourites button, the function still works, where they actually should be redirected to the login page instead.

**Comment by MalaikaQ** [comment]
> When the user is not logged in, clicking the "Add to favourites" button still works, and the listing will be marked as favourite.
> 
> ![image](https://private-user-images.githubusercontent.com/57166217/316583055-d0a726b2-c754-42f0-bf5a-042bbf0b25a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjczMzMsIm5iZiI6MTcxMTQyNzAzMywicGF0aCI6Ii81NzE2NjIxNy8zMTY1ODMwNTUtZDBhNzI2YjItYzc1NC00MmYwLWJmNWEtMDQyYmJmMGIyNWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA0MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOTY0ZjFhN2MzZWFiZmMyYTQ0OGQ0MjA4OTY1NTAwOTFmYmIzYjNlNWY5YmI1Y2JkZmNhNGI5ZjI2ZWFkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-jwdYjgKwIAGTqiupP6JVrM6qV-ZXBJrVFA-xCwwPw8)
> 
> This seems to be caused by the `is_favourite` attribute in the properties table in db. This means that every single person who is visiting the website will share a single favourite collection. I don't think this is the intended behavior.

I was not able to fix this, I will work on this in the next iteration.

**Comment by kzcheng** [comment]
If this isn't fixed yet, we should probably try to fix this in iteration 3 too.

**Comment by MalaikaQ** [comment]
This issue should be fixed.
