### ISSUE TITLE
Remove the deadlinks on Admin Pages

### ISSUE THREAD

**Issue by namneyugn21** [CMPT276-Project-Group-6/Realtorest#121]
Just a bunch of deadlinks in the admin page that need the correct pathing. 
Should also have a feature where admin can add a new property. (path to dev/properties).

**Comment by drishty02** [comment]
I removed the dead links from the admin page. I think it should be ok now.

**Comment by kzcheng** [comment]
Drishty and Amrit worked on this and it should done now.
