### ISSUE TITLE
Filter and Sorting Bar Troubleshoot

### ISSUE THREAD

**Issue by namneyugn21** [CMPT276-Project-Group-6/Realtorest#122]
After clicking on the apply filter, the filter bar should still displays the filter choice. For example, choosing the filter price from High to Low and clicking 'Apply Filter' will simply display the property from high price to low price, but the filter bar still display Low to High, but it should says High to Low; this might be confusing to the user.

**Comment by namneyugn21** [comment]
I also found another bug: the filter might now functioning, as it does not filter out the property that has less than 3 bathroom when user only looking for 3 bathroom or more.

**Comment by drishty02** [comment]
I just made a pull request with the fix and changes. Now after clicking on the apply filter, the filter bar still displays the filter choice.

**Comment by kzcheng** [comment]
> I also found another bug: the filter might now functioning, as it does not filter out the property that has less than 3 bathroom when user only looking for 3 bathroom or more.

Progress have been made, but it seems like the issue with this still exists.

**Comment by drishty02** [comment]
I fixed the bedr and bathr issue. There is on issue, take a scenario where user choose bedr = 2+ and bathr = 3+. It will still show the 2+ bedroom and whatever bathroom associated with (does not matter if it is less than 3) becuase of bedroom filter. I am not sure if this is an issue or is it fine?

**Comment by drishty02** [comment]
I tried to fix this issue as well. please check it and lemme know. I made pull requests.

**Comment by namneyugn21** [comment]
checked, merged, done!
