### ISSUE TITLE
Make a mortgage calculator

### ISSUE THREAD

**Issue by namneyugn21** [CMPT276-Project-Group-6/Realtorest#133]
Check Github Gist for the Mortgage calculator

**Comment by kzcheng** [comment]
Minor correction to this, but I don't think we will be using an API for this.

As in, the mortgage calculator is likely gonna just be some simple Javascript calculations where you can input some numbers and give you a response in number.

So there isn't really any data we need to obtain from anywhere.

**Comment by Htoor1999** [comment]
I can do this

**Comment by kzcheng** [comment]
Done by #197
