### ISSUE TITLE
Incorporating an external API to send emails out

### ISSUE THREAD

**Issue by namneyugn21** [CMPT276-Project-Group-6/Realtorest#135]
Mailing list feature to send emails out using an external API (likely Mailgun)

**Comment by kzcheng** [comment]
I'm gonna check this one out. Should be easy! *[citation needed]*

But yeah, I think I'll begin with trying out Mailgun first.

**Comment by kzcheng** [comment]
Also although I checked this item out, I'm gonna need to procrastinate for a few days first. I'll likely be able to begin working on this on Sunday the 31st. Then it will take me... around 3-5 days?

No idea lol, but should be fine.

**Comment by kzcheng** [comment]
Ok, everything looks to be progressing fine.

![image](https://github.com/CMPT276-Project-Group-6/Realtorest/assets/57166217/b1ce92a3-85f3-4041-9cca-9335209456c4)

**Comment by kzcheng** [comment]
In progress now:
#144

**Comment by kzcheng** [comment]
I really fucking hate that linking a pull request to an issue will automatically close the issue when the pull request is merged...

But yeah, issue with GitHub, oh well.

**Comment by kzcheng** [comment]
Ok, currently it's Tuesday morning at 5 AM, I can't really fall asleep. So I'm gonna work on this a bit more.

Since I'm a bit stuck, I'm gonna just use the Issue posts as rubber duckies and start blogging here a bit. Should help me get my thoughts together.

**Comment by kzcheng** [comment]
So, what I'm trying to do, is to use Mailgun to send emails to a list of email addresses. This should be possible and shouldn't be too difficult. However, it's been quite a long time since I last did this, and I'm not that good at Java, so I'm gonna need to "go figure".

**Comment by kzcheng** [comment]
Altho this might later prove to cause more problems, I think I'm gonna need to sub divide this task a bit into multiple Issues posts. Just as a way to help my own brain process, and keep my code up to date with the new changes in main.

**Comment by kzcheng** [comment]
#148 is also done now.

But it's starting to feel a bit stupid to make a new Issue post every time I want to write a simple thing... I'm gonna stop doing this.

**Comment by kzcheng** [comment]
Ok, I think this is basically all done now.

**Comment by kzcheng** [comment]
#149

**Comment by kzcheng** [comment]
Ok, merged the pull request!

Now, it's time to use my ultimate ninjutsu!

"Shifting the Goal Post and Create More Issues Post Because This Issues Post Isn't Really That Detailed When It Was Created"-jutsu!

Gonna change this to be "make API work" instead of implementing the whole functionality of mailing lists lol

**Comment by kzcheng** [comment]
Which means... Issue is done!
