### ISSUE TITLE
External API: Google Maps API

### ISSUE THREAD

**Issue by namneyugn21** [CMPT276-Project-Group-6/Realtorest#138]
Using Google Maps API to located the property.

**Comment by namneyugn21** [comment]
done!

**Comment by kzcheng** [comment]
Thank you so much Nam!

I checked it, it looks great!

**Comment by kzcheng** [comment]
![image](https://github.com/CMPT276-Project-Group-6/Realtorest/assets/57166217/008665c1-bed8-4d5f-95bf-36b103355e59)
