### ISSUE TITLE
Favourites page can still be seen by clicking the "back" button after logging out

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#152]
The favourites page should only be able to be seen by logged in users.

However, after logging out, if you click the browser's back button, you can go back and see the same page again.

**Comment by drishty02** [comment]
I fixed this issue, now clicking back after logout  is not showing the favourites page, instead it shows the home page. I  made a pull request for that. Please somebody take a look and merge it into the main.
