### ISSUE TITLE
The properties management functionalities of the admin pages still needs its own UI

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#162]
Basically, the properties management pages for admins now is just using the dev pages for the properties database.

![image](https://github.com/CMPT276-Project-Group-6/Realtorest/assets/57166217/47aa4534-2e6d-4746-a497-e800fca178a1)

Which looks a bit out of place compared to everything else.

And the URL is `/dev/properties`, which means it will be disabled once this actually hits production.

**Comment by namneyugn21** [comment]
doneeeeeeeeeeeeeeeeeeeeeeee!

**Comment by namneyugn21** [comment]
still need to find a way to add picture tho
