### ISSUE TITLE
Mailing List UI and User Setting Page

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#163]
![image](https://github.com/CMPT276-Project-Group-6/Realtorest/assets/57166217/a5812d1f-faf4-4649-b8c9-a41055978680)

The functionality for mailing lists is finally done, and can be found on `/dev/mail`.

However, an actual UI for this on the admin pages still needs to be made.

**Comment by namneyugn21** [comment]
done!

**Comment by kzcheng** [comment]
Completed by #185.

We still need a UI for mailing stuff out tho.
