### ISSUE TITLE
Admin page for creating new property listings might have a visual bug

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#201]
![image](https://github.com/CMPT276-Project-Group-6/Realtorest/assets/57166217/ad00a9d1-dc7d-4611-86d5-488a26f9f4e9)

The drop down here looks a bit funny, seems like all the text are white on white background?

**Comment by namneyugn21** [comment]
yeah I know what's wrong lol, my bad...

**Comment by kzcheng** [comment]
Fixed by Nam, nice!
