### ISSUE TITLE
Create a home page

### ISSUE THREAD

**Issue by namneyugn21** [CMPT276-Project-Group-6/Realtorest#30]
:)

**Comment by kzcheng** [comment]
I checked in with Drishty, seems like she's almost done with her part now.

She should be able to make a pull request tomorrow, we'll see if it works.

**Comment by kzcheng** [comment]
Nice and clean! The home page seems to be working!

![image](https://github.com/CMPT276-Project-Group-6/Realtorest/assets/57166217/08d83e89-6ac0-42f3-804a-185cda66e157)

**Comment by kzcheng** [comment]
Ok, merged everything now.

**Comment by kzcheng** [comment]
Did a bit of refactoring after this.
