### ISSUE TITLE
Make the UI for displaying property listings

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#32]

**Comment by kzcheng** [comment]
Nam is still working on this, and it should be on track.

He should be able to get it done tomorrow. And together with Drishty's part in #30, we should be able to have a pretty nice looking UI to base future work on.

**Comment by namneyugn21** [comment]
Just finish the first draft. Everything should be sufficient for the first iteration. In the meantime, I will continue to add more design and features for this page.

**Comment by kzcheng** [comment]
Ok, this is done now, nice!

**Comment by kzcheng** [comment]
Some more refactoring is done.
