### ISSUE TITLE
"Add to favorites" feature

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#70]
After logging in, users will need to be able to add listed properties into a "favorites" collection, they should later be able to see a list of all their favorited properties somewhere.

**Comment by kzcheng** [comment]
Malaika plans to work on the "add to favorites" feature. This means creating a way to store a list of favorites in the database, and implement functionality to read and write this information.

Malaika will likely be able to complete this before the end of Friday 22nd.

**Comment by kzcheng** [comment]
To do this, the user database will need to change and be able to store a list of property IDs.

**Comment by MalaikaQ** [comment]
Made a pull request for showing, adding and removing favourited listings as well as unit testing for the features.

**Comment by kzcheng** [comment]
> Made a pull request for showing, adding and removing favourited listings as well as unit testing for the features.

Nice work! I'll go take a look!

**Comment by kzcheng** [comment]
Completed by Malaika with pull request.

**Comment by kzcheng** [comment]
Some issues still exist, gonna document them later.
