### ISSUE TITLE
"Featured listing" section on top of property listings page

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#73]
The client mentioned that he wants to list all the listening on Vancouver island and then he wants to have featured listing section to list the ones that he is selling.

**Comment by kzcheng** [comment]
Not sure what's the best way to do this, gonna need some discussion.

**Comment by namneyugn21** [comment]
It can be either we are going to have ANOTHER database for the featured listing, or we just manually do it in HTML... I think the database would be better but I afraid we don't have enough time

**Comment by kzcheng** [comment]
> It can be either we are going to have ANOTHER database for the featured listing, or we just manually do it in HTML... I think the database would be better but I afraid we don't have enough time

I would say the best way is to have an attribute in the property listings table. Like, if this is a featured listing or not.

So if a property have this attribute set to on, display it in the featured listings section.

**Comment by kzcheng** [comment]
Nam will be working on this, nice!

**Comment by namneyugn21** [comment]
done!
plan changed: featured listing will be in homepage.
