### ISSUE TITLE
Check the user's password strength when registering

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#74]
Bobby said this is a good idea. We can probably do this.

Just something simple, like pure numbers not being allowed.

This isn't a priority so doing this in Iteration 3 should also be fine.

**Comment by MalaikaQ** [comment]
Check password strength 
           - having a minimum amount of characters
           - having a sign
           - having numbers

**Comment by kzcheng** [comment]
> Check password strength - having a minimum amount of characters - having a sign - having numbers

Nice! This looks good!

**Comment by MalaikaQ** [comment]
Pull request for feature checking if password has a min amount of characters, lowercase letter, number and special character when registering.

**Comment by kzcheng** [comment]
Pull request merged, this is done now.
