### ISSUE TITLE
Clicking "back" after logging in still shows the login page

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#76]
Seems like clicking "back" can allow you to still see the login page. In theory, this should redirect to the home page.

This is weird.

**Comment by kzcheng** [comment]
Yeah this is probably something we should priorities fixing more, since it's something the TAs have told every group.

**Comment by drishty02** [comment]
I fixed this issue, now clicking back shows the home page with session. I made a pull request please take look.
