### ISSUE TITLE
User stories for iteration 2

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#77]
As mentioned by Bobby:
> For the writeups:
> Make sure each story provides a value for a type of user. For example, “user interface” should not be a story as no actions are associated with value.
> Stories should be more structured. For clarity, try splitting them into subsections such as preconditions, postconditions, tests, actions, etc.

And as mentioned by Rithik:
> I recommend writing the stories with slightly more structure (i.e. pre/post conditions, test, actions, etc). This will help later int he process :)

So yeah, we should probably reformat the user stories a bit later.

**Comment by drishty02** [comment]
I will write user stories on the feature I am working, that is filters on the listing page, if i get more time, i will write some for mortgage cacl.

**Comment by kzcheng** [comment]
> I wil focus on pre/post conditions, test and actions that will help in implementing the functions.

Also Drishty, can you also improve the user stories for iteration 1?

Since we are losing marks from having bad user stories.

**Comment by kzcheng** [comment]
Here is the Google Docs to work on it:

https://docs.google.com/document/d/1_oOKkc0if6xlwWooyd694t9nAQmbeQBu31ZJ956VdmE/edit

And remember to use the Iteration 2 color for new stuff added.

**Comment by drishty02** [comment]
I wrote 5 user stories covering all the important points I mentioned before and I also referred to the user story example from the lecture notes to make sure I am on the right track.

**Comment by kzcheng** [comment]
> I wrote 5 user stories covering all the important points I mentioned before and I also referred to the user story example from the lecture notes to make sure I am on the right track.

Nice work!

I saw the 5 user stories for iteration 2 now!

**Comment by kzcheng** [comment]
Since the user stories seems like they are no longer being updated for now. I'm gonna close the issue and make some new ones for the next steps we need to do.
