### ISSUE TITLE
Pop up window after the user have been using a website for a while that asks for contact information

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#78]
The client wants to have a pop up window appear if the user have been using the website for 5 to 10 min and not logged in. The pop up window should prompt the user to enter things like their name, email, contact phone number, etc.

It's undecided if the user should be able to continue to use the website by closing this pop up, or if they need to deal with it.

**Comment by namneyugn21** [comment]
I think we should let them use it lol, it's kinda mean and not good practice to just prevent them to continue to see :))))

**Comment by kzcheng** [comment]
> I think we should let them use it lol, it's kinda mean and not good practice to just prevent them to continue to see :))))

Agree, it's pretty weird to not allow people to keep using the site.

**Comment by MalaikaQ** [comment]
I have coded it so that the user gets the popup after inactivity but I will change it so that it occurs when not signed in and improve the UI. The user is able to close the popup if they don't want to share their information.

**Comment by kzcheng** [comment]
> I have coded it so that the user gets the popup after inactivity but I will change it so that it occurs when not signed in and improve the UI. The user is able to close the popup if they don't want to share their information.

I see, thanks!

Also, I think even if they are active, they should still see the popup? Not sure.

**Comment by kzcheng** [comment]
Completed by Malaika.
