### ISSUE TITLE
Update user stories of iteration 1 to include preconditions, postconditions, tests, actions, etc

### ISSUE THREAD

**Issue by kzcheng** [CMPT276-Project-Group-6/Realtorest#98]
Continuation of #77.

As mentioned by Bobby:
> For the writeups:
> Make sure each story provides a value for a type of user. For example, “user interface” should not be a story as no actions are associated with value.
> Stories should be more structured. For clarity, try splitting them into subsections such as preconditions, postconditions, tests, actions, etc.

And as mentioned by Rithik:
> I recommend writing the stories with slightly more structure (i.e. pre/post conditions, test, actions, etc). This will help later int he process :)

Drishty have already done some user stories for iteration 2. However, the old user stories for iteration 1 still needs to be updated.

**Comment by kzcheng** [comment]
Worked on this a bit, it's feeling more and more confusing.

I've sent Bobby an email asking for some help. Hope he gets back to me.

**Comment by kzcheng** [comment]
More advice from Bobby:
> The formatting for the stories will be different for every group. Generally, they should include the important parts such as pre/post conditions, actions, tests, acceptance criteria, etc., but you may also choose to include other subsections such as risk analysis or extra notes. The most important thing is to keep the formatting consistent.

**Comment by kzcheng** [comment]
Drishty said she will work on this a bit more today.

**Comment by namneyugn21** [comment]
I also fixed the structure too

**Comment by drishty02** [comment]
I added more explanation to the user stories. I could not find the It1 user stories in that document. If somebody sees it please let me know. I tried to find it.

**Comment by drishty02** [comment]
I structured the future user stories as well. Adding more details and explanation.

**Comment by namneyugn21** [comment]
done for I2!
